version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: eve_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: eve
      POSTGRES_USER: eve
      POSTGRES_PASSWORD: eve
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eve_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=eve
      - DB_PASSWORD=eve
      - DB_NAME=eve
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: eve_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    restart: always